name       : mozjs38
version    : 38.8.0
release    : 1
source     :
    - https://ftp.mozilla.org/pub/firefox/releases/38.8.0esr/source/firefox-38.8.0esr.source.tar.bz2 : 9475adcee29d590383c4885bc5f958093791d1db4302d694a5d2766698f59982
homepage   : http://mozilla.org
license    :
    - GPL-2.0
    - MPL-1.1
component  : desktop.library
summary    : JS is Mozilla's JavaScript engine written in C/C++
description: |
    JS is Mozilla's JavaScript engine written in C/C++
libsplit   : no
builddeps  :
    - pkgconfig(nspr)
setup      : |
    export PYTHON=/usr/bin/python2
    %apply_patches
    head -n -1 config/milestone.txt > config/milestone.txt
    echo "${version}" >> config/milestone.txt
    cd $workdir/js/src
    %configure --enable-readline \
               --enable-threadsafe \
               --enable-shared-js \
               --with-system-ffi \
               --with-system-nspr
build      : |
    export PYTHON=/usr/bin/python2
    cd $workdir/js/src
    %make
install    : |
    export PYTHON=/usr/bin/python2
    cd $workdir/js/src
    %make_install
    rm -r $installdir/%libdir%/*.ajs
